language: go
go:
  - 1.8.x
  - 1.9.x
sudo: false
install:
  - go get -d -t -v ./...
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - export PATH=$PATH:$HOME/go/bin
  - ./goclean.sh
